package com.blood.donation.app.enums;

@SuppressWarnings("SpellCheckingInspection")
public enum City {
    AFOURAR("Afourar"),
    AGADIR("Agadir"),
    AGDZ("Agdz"),
    AGHBALA("Aghbala"),
    AGHBALOU_NSSARDANE("Aghbalou Nssardane"),
    AGOURAI("Agourai"),
    AGUELMOUS("Aguelmous"),
    AHFIR("Ahfir"),
    AHRARA("Ahrara"),
    AIN_BNI_MATHAR("Ain Bni Mathar"),
    AIN_CHEGGAG("Ain Cheggag"),
    AIN_DORIJ("Ain Dorij"),
    AIN_EL_AOUDA("Ain El Aouda"),
    AIN_ERREGGADA("Ain Erreggada"),
    AIN_HARROUDA("Ain Harrouda"),
    AIN_JEMAA("Ain Jemaa"),
    AIN_KARMA("Ain Karma"),
    AIN_LEUH("Ain Leuh"),
    AIN_TAOUJDATE("Ain Taoujdate"),
    AIT_BAHA("Ait Baha"),
    AIT_DAOUD("Ait Daoud"),
    AIT_IAAZA("Ait Iaaza"),
    AIT_ISHAQ("Ait Ishaq"),
    AIT_MELLOUL("Ait Melloul"),
    AIT_OURIR("Ait Ourir"),
    AJDIR("Ajdir"),
    AKKA("Akka"),
    AKLIM("Aklim"),
    AKNOUL("Aknoul"),
    AL_AAROUI("Al Aaroui"),
    ALNIF("Alnif"),
    AMALOU_IGHRIBEN("Amalou Ighriben"),
    AMIZMIZ("Amizmiz"),
    AOUFOUS("Aoufous"),
    AOULOUZ("Aoulouz"),
    AOURIR("Aourir"),
    ARBAOUA("Arbaoua"),
    ARFOUD("Arfoud"),
    ASILAH("Asilah"),
    ASSA("Assa"),
    ASSAHRIJ("Assahrij"),
    AZEMMOUR("Azemmour"),
    AZILAL("Azilal"),
    AZROU("Azrou"),
    BAB_BERRAD("Bab Berrad"),
    BAB_TAZA("Bab Taza"),
    BEN_AHMED("Ben Ahmed"),
    BEN_GUERIR("Ben Guerir"),
    BEN_SLIMANE("Ben Slimane"),
    BEN_TAIEB("Ben Taieb"),
    BENI_MELLAL("Beni Mellal"),
    BENI_YAKHLEF("Beni Yakhlef"),
    BERKANE("Berkane"),
    BERRECHID("Berrechid"),
    BHALIL("Bhalil"),
    BIN_ANSAR("Bin Ansar"),
    BIOUGRA("Biougra"),
    BIR_JDID("Bir Jdid"),
    BNI_BOUAYACH("Bni Bouayach"),
    BNI_CHIKER("Bni Chiker"),
    BNI_DRAR("Bni Drar"),
    BNI_HADIFA("Bni Hadifa"),
    BNI_TADJITE("Bni Tadjite"),
    BOUANANE("Bouanane"),
    BOUARFA("Bouarfa"),
    BOUDERBALA("Bouderbala"),
    BOUDNIB("Boudnib"),
    BOUGUEDRA("Bouguedra"),
    BOUHDILA("Bouhdila"),
    BOUIZAKARN("Bouizakarn"),
    BOUIZAZARENE_IHADDADENE("BouiZazarene Ihaddadene"),
    BOUJAD("Boujad"),
    BOUJNIBA("Boujniba"),
    BOUKNADEL("Bouknadel"),
    BOULANOUARE("Boulanouare"),
    BOULEMANE("Boulemane"),
    BOUMALNE_DADES("Boumalne Dades"),
    BOUMIA("Boumia"),
    BOUSKOURA("Bouskoura"),
    BOUZNIKA("Bouznika"),
    BRADIA("Bradia"),
    BRIKCHA("Brikcha"),
    BZOU("Bzou"),
    CAPE_BOJADOR("Cape Bojador"),
    CASABLANCA("Casablanca"),
    CHEFCHAOUEN("Chefchaouen"),
    CHICHAOUA("Chichaoua"),
    DAKHLA("Dakhla"),
    DAR_BNI_KARRICH("Dar Bni Karrich"),
    DAR_EL_KEBDANI("Dar El Kebdani"),
    DAR_GUEDDARI("Dar Gueddari"),
    DAR_OULD_ZIDOUH("Dar Ould Zidouh"),
    DEBDOU("Debdou"),
    DEMNATE("Demnate"),
    DEROUA("Deroua"),
    DRARGA("Drarga"),
    DRIOUCH("Driouch"),
    ECHEMMAIA("Echemmaia"),
    EL_AIOUN_SIDI_MELLOUK("El Aioun Sidi Mellouk"),
    EL_BOROUJ("El Borouj"),
    EL_GARA("El Gara"),
    EL_GUERDAN("El Guerdan"),
    EL_HAJEB("El Hajeb"),
    EL_HANCHANE("El Hanchane"),
    EL_KBAB("El Kbab"),
    EL_KELAA_DES_SRAGHNA("El Kelaa des Sraghna"),
    EL_KSIBA("El Ksiba"),
    EL_MARSA("El Marsa"),
    EL_MENZEL("El Menzel"),
    EL_OUATIA("El Ouatia"),
    ERRICH("Errich"),
    ERRACHIDIA("Errachidia"),
    ESSAOUIRA("Essaouira"),
    FAM_EL_HISN("Fam El Hisn"),
    FARKHANA("Farkhana"),
    FES("Fes"),
    FIGUIG("Figuig"),
    FKIH_BEN_SALEH("Fkih Ben Saleh"),
    FNIDEQ("Fnideq"),
    FOUM_JAMAA("Foum Jamaa"),
    FOUM_ZGUID("Foum Zguid"),
    GHAFSAI("Ghafsai"),
    GOULMIMA("Goulmima"),
    GOURRAMA("Gourrama"),
    GUELMIM("Guelmim"),
    GUERCIF("Guercif"),
    GUEZNAIA("Gueznaia"),
    GUIGOU("Guigou"),
    GUISSER("Guisser"),
    HAD_BOUHSSOUSSEN("Had Bouhssoussen"),
    HAD_KOURT("Had Kourt"),
    HADJ_KADDOUR("Hadj Kaddour"),
    HARHOURA("Harhoura"),
    HATTANE("Hattane"),
    HOCEIMA("Hoceima"),
    IFRAN("Ifran"),
    IGHOUD("Ighoud"),
    IMINTANOUTE("Imintanoute"),
    IMOUZZER_KANDAR("Imouzzer Kandar"),
    IMOUZZER_MARMOUCHA("Imouzzer Marmoucha"),
    IMZOUREN("Imzouren"),
    INZEGAN("Inzegan"),
    IRHERM("Irherm"),
    ISSAGUEN("Issaguen"),
    ITZER("Itzer"),
    JAADAR("Jaadar"),
    JDIDA("Jdida"),
    JEBHA("Jebha"),
    JERADA("Jerada"),
    JMAAT_SHAIM("Jmaat Shaim"),
    JORF("Jorf"),
    JORF_EL_MELHA("Jorf El Melha"),
    KARIA("Karia"),
    KARIA_BA_MOHAMED("Karia Ba Mohamed"),
    KARIAT_ARKMANE("Kariat Arkmane"),
    KASBAT_TADLA("Kasbat Tadla"),
    KASSITA("Kassita"),
    KEHF_NSOUR("Kehf Nsour"),
    KELAT_MEGNOUNA("Kelat Megnouna"),
    KENITRA("Kenitra"),
    KEROUNA("Kerouna"),
    KERROUCHEN("Kerrouchen"),
    KETTARA("Kettara"),
    KHEMIS_SAHEL("Khemis Sahel"),
    KHEMISSET("Khemisset"),
    KHENIFRA("Khenifra"),
    KHNICHET("Khnichet"),
    KHOURIBGA("Khouribga"),
    KSAR_EL_KBIR("Ksar El Kbir"),
    LAAKARTA("Laakarta"),
    LAAOUNATE("Laaounate"),
    LAATTAOUIA("Laattaouia"),
    LAAYOUNE("Laayoune"),
    LAGOUIRA("Lagouira"),
    LAHRAOUYINE("Lahraouyine"),
    LAKHSAS("Lakhsas"),
    LALLA_MIMOUNA("Lalla Mimouna"),
    LALLA_TAKERKOUST("Lalla Takerkoust"),
    LAMKANSA("Lamkansa"),
    LARACHE("Larache"),
    LOUDAYA("Loudaya"),
    LOULAD("Loulad"),
    LQLIAA("Lqliaa"),
    MDIQ("Mdiq"),
    MRIRT("MRirt"),
    MAAZIZ("Maaziz"),
    MADAGH("Madagh"),
    MARRAKESH("Marrakesh"),
    MARTIL("Martil"),
    MASSA("Massa"),
    MATMATA("Matmata"),
    MECHRA_BEL_KSIRI("Mechra Bel Ksiri"),
    MEDIOUNA("Mediouna"),
    MEHDYA("Mehdya"),
    MEKNES("Meknes"),
    MHAYA("Mhaya"),
    MIDAR("Midar"),
    MIDELT("Midelt"),
    MISSOUR("Missour"),
    MOHAMMEDIA("Mohammedia"),
    MOQRISSET("Moqrisset"),
    MOULAY_ABDALLAH("Moulay Abdallah"),
    MOULAY_BOUAZZA("Moulay Bouazza"),
    MOULAY_BOUSSELHAM("Moulay Bousselham"),
    MOULAY_BRAHIM("Moulay Brahim"),
    MOULAY_DRISS_ZERHOUN("Moulay Driss Zerhoun"),
    MOULAY_YACOUB("Moulay Yacoub"),
    NZALAT_BNI_AMAR("NZalat Bni Amar"),
    NADOR("Nador"),
    NAIMA("Naima"),
    NOUACEUR("Nouaceur"),
    OUAD_LAOU("Ouad Laou"),
    OUALIDIA("Oualidia"),
    OUAOUIZERT("Ouaouizert"),
    OUARZAZATE("Ouarzazate"),
    OUAZZANE("Ouazzane"),
    OUED_AMLIL("Oued Amlil"),
    OUED_EL_HEIMAR("Oued El Heimar"),
    OUJDA("Oujda"),
    OULAD_ABBOU("Oulad Abbou"),
    OULAD_AMRANE("Oulad Amrane"),
    OULAD_AYAD("Oulad Ayad"),
    OULAD_BERHIL("Oulad Berhil"),
    OULAD_GHADBANE("Oulad Ghadbane"),
    OULAD_HRIZ_SAHEL("Oulad Hriz Sahel"),
    OULAD_MRAH("Oulad MRah"),
    OULAD_MBAREK("Oulad Mbarek"),
    OULAD_SAID("Oulad Said"),
    OULAD_TAYEB("Oulad Tayeb"),
    OULAD_TEIMA("Oulad Teima"),
    OULAD_YAICH("Oulad Yaich"),
    OULAD_ZBAIR("Oulad Zbair"),
    OULED_FREJ("Ouled Frej"),
    OULMES("Oulmes"),
    OUNAGHA("Ounagha"),
    OUTAT_EL_HAJ("Outat El Haj"),
    RABAT("Rabat"),
    RAS_EL_AIN("Ras El Ain"),
    RAS_KEBDANA("Ras Kebdana"),
    RIBAT_EL_KHEIR("Ribat El Kheir"),
    RISSANI("Rissani"),
    ROMMANI("Rommani"),
    SABAA_AIYOUN("Sabaa Aiyoun"),
    SAFI("Safi"),
    SAIDIA("Saidia"),
    SALE("Sale"),
    SEBT_GZOULA("Sebt Gzoula"),
    SEBT_JAHJOUH("Sebt Jahjouh"),
    SEBT_LAMAARIF("Sebt Lamaarif"),
    SEFROU("Sefrou"),
    SEGANGAN("Segangan"),
    SELOUANE("Selouane"),
    SETTAT("Settat"),
    SID_LMOKHTAR("Sid LMokhtar"),
    SID_ZOUINE("Sid Zouine"),
    SIDI_ABDALLAH_GHIAT("Sidi Abdallah Ghiat"),
    SIDI_ADDI("Sidi Addi"),
    SIDI_AHMED("Sidi Ahmed"),
    SIDI_ALI_BEN_HAMDOUCHE("Sidi Ali Ben Hamdouche"),
    SIDI_ALLAL_EL_BAHRAOUI("Sidi Allal El Bahraoui"),
    SIDI_ALLAL_TAZI("Sidi Allal Tazi"),
    SIDI_BENNOUR("Sidi Bennour"),
    SIDI_BOU_OTHMANE("Sidi Bou Othmane"),
    SIDI_BOUBKER("Sidi Boubker"),
    SIDI_BOUZID("Sidi Bouzid"),
    SIDI_IFNI("Sidi Ifni"),
    SIDI_JABER("Sidi Jaber"),
    SIDI_KACEM("Sidi Kacem"),
    SIDI_RAHAL("Sidi Rahal"),
    SIDI_RAHEL_CHATAI("Sidi Rahel Chatai"),
    SIDI_SLIMANE("Sidi Slimane"),
    SIDI_SLIMANE_ECHCHARRAA("Sidi Slimane Echcharraa"),
    SIDI_SMAIL("Sidi Smail"),
    SIDI_TAIBI("Sidi Taibi"),
    SIDI_YAHYA_EL_GHARB("Sidi Yahya El Gharb"),
    SKHINATE("Skhinate"),
    SKHIRAT("Skhirat"),
    SKHOUR_RHAMNA("Skhour Rhamna"),
    SKOURA("Skoura"),
    SMARA("Smara"),
    SMIMOU("Smimou"),
    SOUALEM("Soualem"),
    SOUK_EL_HAD("Souk El Had"),
    SOUK_LARBAA("Souk Larbaa"),
    SUQ_SEBT_OULAD_NAMA("Suq Sebt Oulad Nama"),
    TABOUNTE("Tabounte"),
    TAFERSIT("Tafersit"),
    TAFETACHTE("Tafetachte"),
    TAFRAWT("Tafrawt"),
    TAGHJIJT("Taghjijt"),
    TAHANNAOUT("Tahannaout"),
    TAHLA("Tahla"),
    TAINASTE("Tainaste"),
    TALIOUINE("Taliouine"),
    TALMEST("Talmest"),
    TALSINT("Talsint"),
    TAMALLALT("Tamallalt"),
    TAMANAR("Tamanar"),
    TAMASSINT("Tamassint"),
    TAMESLOUHT("Tameslouht"),
    TANTAN("Tantan"),
    TANGIER("Tangier"),
    TAOUIMA("Taouima"),
    TAOUNATE("Taounate"),
    TAOURIRT("Taourirt"),
    TARFAYA("Tarfaya"),
    TARGUIST("Targuist"),
    TAROUDANT("Taroudant"),
    TATA("Tata"),
    TAZA("Taza"),
    TAZNAKHT("Taznakht"),
    TEMARA("Temara"),
    TEMSIA("Temsia"),
    TENDRARA("Tendrara"),
    TETOUAN("Tetouan"),
    THAR_ESSOUK("Thar Essouk"),
    TIDDAS("Tiddas"),
    TIFELT("Tifelt"),
    TIGHASSALINE("Tighassaline"),
    TIGHZA("Tighza"),
    TIMAHDITE("Timahdite"),
    TINGHIR("Tinghir"),
    TINJDAD("Tinjdad"),
    TISSA("Tissa"),
    TIT_MELLIL("Tit Mellil"),
    TIZI_OUASLI("Tizi Ouasli"),
    TIZNIT("Tiznit"),
    TIZTOUTINE("Tiztoutine"),
    TNIN_SIDI_LYAMANI("Tnin Sidi Lyamani"),
    TOUISSIT("Touissit"),
    TOUNFIT("Tounfit"),
    WAD_ZAM("Wad Zam"),
    YOUSSOUFIA("Youssoufia"),
    ZAG("Zag"),
    ZAGORA("Zagora"),
    ZAIDA("Zaida"),
    ZAIO("Zaio"),
    ZAOUIAT_BOUGRIN("Zaouiat Bougrin"),
    ZAWIYAT_CHEIKH("Zawiyat cheikh"),
    ZIRARA("Zirara"),
    ZMAMRA("Zmamra"),
    ZOUMI("Zoumi"),
    ZRARDA("Zrarda");


    private final String value;

    City(String value) {
        this.value = value;
    }

    public final String value() { return this.value; }

    public static City fromValue (String value) {
        for(City requestName : City.values())
            if(requestName.value.equals(value)) return requestName;
        return null;
    }
}
